name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: "eu"
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_SA_ZIP_URL: ${{secrets.SA_ZIP_URL}}
          HD_CREDENTIALS: ${{secrets.CREDENTIALS}}
          HD_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          HD_CONFIG_URL: ${{secrets.CONFIG_URL}}
          HD_MAX_CONCURRENT_DOWNLOADS: ${{secrets.MAX_CONCURRENT_DOWNLOADS}}
  restart:
    needs: [deploy]
    name: Restart Worker Dyno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: |
            heroku ps:scale worker=0 --app ${{secrets.HEROKU_APP_NAME}}
            heroku ps:scale worker=1 --app ${{secrets.HEROKU_APP_NAME}}